### ISSUE TITLE
Create one-to-one interfacer strategy

### ISSUE THREAD

**Issue by victordfb** [tunguski/interfacer#3]
It would be great if was possible to specify which class would implement which interface, e.g.:

```
<configuration>
    <interfacesDirectory>${project.basedir}/src/main/java</interfacesDirectory>
    <interfacePackage>pl.matsuo.interfacer.showcase</interfacePackage>
    <mappings>
        <mapping>test.package.AvroGeneratedClass1:my.package.MyInterface1</mapping>
        <mapping>test.package.AvroGeneratedClass2:my.package.MyInterface2</mapping>
        <mapping>test.package.AvroGeneratedClass3:my.package.MyInterface1</mapping>
    </mappings>
</configuration>
```

**Comment by tunguski** [comment]
Hi Victor,

Thanks for your feedback!

The main idea of this plugin is **to detect** classes that extend specified interfaces and to add these interfaces to class definitions.

I may misunderstood your proposal, but my guess is that you don't want to detect anything rather force-add an interface to a class declaration. If so, then you can easily achieve it right now with a simple string replacement, e.g.: https://stackoverflow.com/questions/15157779/maven-replacer-plugin-and-multiple-files.

I agree this is more primitive approach (instead of saying "add interface to class" one have to say "replace `class ClassName` with `class ClassName implements InterfaceName`). But the advantage is it is achievable right now without any coding.

If you still think it's worth extending this plugin, it would be great if you could describe your use case and how the current approach is problematic there. This way it will be easier for me to understand what change would be most valuable to the plugin.

Thanks!
